displayName=HCIM Safety Check
author=Urzael
description=A plugin that changes the HCIM chat icon from red to green while inside known safe death areas.
tags=ironman, hcim, hardcore ironman, im, death, tool, chat icon, helmet icon
version=
plugins=com.hcimsafetycheck.HCIMSafetyCheckPlugin
build=standard